# Generated by Django 4.2.2 on 2023-06-09 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.TextField()),
                ('data', models.TextField()),
                ('img', models.ImageField(upload_to='profile')),
                ('isLoged', models.TextField(default='False')),
                ('firebaseId', models.TextField()),
                ('contacts', models.TextField()),
            ],
        ),
    ]
